<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="accordion-my">
    <div class="bodys">
    <div class="title">My accordion widget</div>
    <div class="content">
        <div data-mage-init='{"myAccordion":{}}' class="accordion">
            <div class="section">
                <div class="section-button">
                    <div class="section-title">Section 1</div>
                    <div class="section-img"></div>
                </div>
                <div class="section-content">
                    <div class="p-content">
                        <p>Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.</p>

                        <!-- ================================================== -->
                        <div class="content">
                            <div data-mage-init='{"myAccordion":{}}' class="accordion">
                                <div class="section">
                                    <div class="section-button">
                                        <div class="section-title">Section 1</div>
                                        <div class="section-img"></div>
                                    </div>
                                    <div class="section-content">
                                        <div class="p-content">
                                            <p>Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="section">
                                    <div class="section-button">
                                        <div class="section-title">Section 2</div>
                                        <div class="section-img"></div>
                                    </div>
                                    <div class="section-content">
                                        <div class="p-content">
                                            <p>Sed non urna. Donec et ante. Phasellus eu ligula. Vestibulum sit amet purus. Vivamus hendrerit, dolor at aliquet laoreet, mauris turpis porttitor velit, faucibus interdum tellus libero ac justo. Vivamus non quam. In suscipit faucibus urna.</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="section">
                                    <div class="section-button">
                                        <div class="section-title">Section 3</div>
                                        <div class="section-img"></div>
                                    </div>
                                    <div class="section-content">
                                        <div class="p-content">
                                            <p>Nam enim risus, molestie et, porta ac, aliquam ac, risus. Quisque lobortis. Phasellus pellentesque purus in massa. Aenean in pede. Phasellus ac libero ac tellus pellentesque semper. Sed ac felis. Sed commodo, magna quis lacinia ornare, quam ante aliquam nisi, eu iaculis leo purus venenatis dui.</p>
                                            <ul class="menu">
                                                <li><a class="menu-one" >List item one</a></li>
                                                <li><a class="menu-two" >List item two</a></li>
                                                <li><a class="menu-three" >List item three</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="section">
                                    <div class="section-button">
                                        <div class="section-title">Section 4</div>
                                        <div class="section-img"></div>
                                    </div>
                                    <div class="section-content">
                                        <div class="p-content">
                                            <p>Cras dictum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia mauris vel est.</p>
                                            <p>Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
                                        </div>

                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section">
                <div class="section-button">
                    <div class="section-title">Section 2</div>
                    <div class="section-img"></div>
                </div>
                <div class="section-content">
                    <div class="p-content">
                        <p>Sed non urna. Donec et ante. Phasellus eu ligula. Vestibulum sit amet purus. Vivamus hendrerit, dolor at aliquet laoreet, mauris turpis porttitor velit, faucibus interdum tellus libero ac justo. Vivamus non quam. In suscipit faucibus urna.</p>
                    </div>
                </div>
            </div>
            <div class="section">
                <div class="section-button">
                    <div class="section-title">Section 3</div>
                    <div class="section-img"></div>
                </div>
                <div class="section-content">
                    <div class="p-content">
                        <p>Nam enim risus, molestie et, porta ac, aliquam ac, risus. Quisque lobortis. Phasellus pellentesque purus in massa. Aenean in pede. Phasellus ac libero ac tellus pellentesque semper. Sed ac felis. Sed commodo, magna quis lacinia ornare, quam ante aliquam nisi, eu iaculis leo purus venenatis dui.</p>
                        <ul class="menu">
                            <li><a class="menu-one" >List item one</a></li>
                            <li><a class="menu-two" >List item two</a></li>
                            <li><a class="menu-three" >List item three</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="section">
                <div class="section-button">
                    <div class="section-title">Section 4</div>
                    <div class="section-img"></div>
                </div>
                <div class="section-content">
                    <div class="p-content">
                        <p>Cras dictum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia mauris vel est.</p>
                        <p>Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
                    </div>
                </div>
            </div>
            <div class="section">
                <div class="section-button">
                    <div class="section-title">Section 5</div>
                    <div class="section-img"></div>
                </div>
                <div class="section-content">
                    <div class="p-content">
                        <p>Nam enim risus, molestie et, porta ac, aliquam ac, risus. Quisque lobortis. Phasellus pellentesque purus in massa. Aenean in pede. Phasellus ac libero ac tellus pellentesque semper. Sed ac felis. Sed commodo, magna quis lacinia ornare, quam ante aliquam nisi, eu iaculis leo purus venenatis dui.</p>
                        <ul class="menu">
                            <li><a class="menu-one" >List item one</a></li>
                            <li><a class="menu-two" >List item two</a></li>
                            <li><a class="menu-three" >List item three</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="section">
                <div class="section-button">
                    <div class="section-title">Section 6</div>
                    <div class="section-img"></div>
                </div>
                <div class="section-content">
                    <div class="p-content">
                        <p>Cras dictum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia mauris vel est.</p>
                        <p>Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- ================================================== -->

<!--    <script type="text/javascript" src="js/accordionWidget.js"></script>-->
    </div>
</div>
