<div data-mage-init='{"mySlick":{
        "dots": true,
        "infinite": true,
        "autoplay": true,
        "speed": 500,
        "slidesToShow": 1
    }}' class="img-baner">
    <div><img src="<?php echo $block->getViewFileUrl('images/1_baner.jpg'); ?>"/></div>
    <div><img src="<?php echo $block->getViewFileUrl('images/2_baner.jpg'); ?>"/></div>
    <div><img src="<?php echo $block->getViewFileUrl('images/3_baner.jpg'); ?>"/></div>
</div>
